### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by dimaspencer84** [the-Infected-Drake/TIDoS-Framework#5]
When chosing the nmap module, I find this error message:
    Traceback (most recent call last):
      File "tidos.py", line 409, in <module>
       thetidosmain()
      File "tidos.py", line 202, in thetidosmain
        nmap()
    TypeError: 'module' object is not callable

**Comment by the-Infected-Drake** [comment]
I actually don't get this at all. Maybe some you can type it once again and check. Also pls remember that this will work only on Linux Systems with Python 2.7

**Comment by dimaspencer84** [comment]
It worked on an another machine. It was on my side then. thanks
